import { Platform } from 'react-native';

/** Subpar design-system color tokens (from SPColors) */
export const SPColors = {
  ink: '#0e2118',
  sub: '#6b756f',
  forest: '#1d4e34',
  greenDeep: '#11371f',
  citron: '#cfde50',
  cream: '#fbf6e6',
  paper: '#f7f4ea',
  rule: '#e2dcc0',
  clay: '#cc6f4a',
  // functional
  toggleOn: '#3aa57c',
  toggleOff: '#cdd0c8',
  dayBtnBg: 'rgba(58,165,124,0.14)',
  dayBtnFg: '#246b4f',
} as const;

export const Colors = {
  light: {
    text: '#11181C',
    textSecondary: '#687076',
    background: '#FFFFFF',
    surface: '#F8F9FA',
    tint: '#2D6A4F',
    accent: '#52B788',
    accentLight: '#D8F3DC',
    icon: '#687076',
    tabIconDefault: '#687076',
    tabIconSelected: '#2D6A4F',
    border: '#E9ECEF',
    progressTrack: '#E9ECEF',
    progressFill: '#52B788',
    ringBackground: '#E9ECEF',
    challengeGradientStart: '#2D6A4F',
    challengeGradientEnd: '#52B788',
    streakBadge: '#F59E0B',
    paceGood: '#52B788',
    paceBehind: '#F59E0B',
    durationGreen: '#52B788',
    durationRed: '#E63946',
    durationBlue: '#457B9D',
    durationAmber: '#F59E0B',
  },
  dark: {
    text: '#ECEDEE',
    textSecondary: '#9BA1A6',
    background: '#0D1B0D',
    surface: '#1A2E1A',
    tint: '#52B788',
    accent: '#52B788',
    accentLight: '#1B4332',
    icon: '#9BA1A6',
    tabIconDefault: '#9BA1A6',
    tabIconSelected: '#52B788',
    border: '#2D3436',
    progressTrack: '#2D3436',
    progressFill: '#52B788',
    ringBackground: '#2D3436',
    challengeGradientStart: '#1B4332',
    challengeGradientEnd: '#52B788',
    streakBadge: '#F59E0B',
    paceGood: '#52B788',
    paceBehind: '#F59E0B',
    durationGreen: '#52B788',
    durationRed: '#E63946',
    durationBlue: '#457B9D',
    durationAmber: '#F59E0B',
  },
};

export const Fonts = Platform.select({
  ios: {
    sans: 'system-ui',
    serif: 'ui-serif',
    rounded: 'ui-rounded',
    mono: 'ui-monospace',
  },
  default: {
    sans: 'normal',
    serif: 'serif',
    rounded: 'normal',
    mono: 'monospace',
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});
